# Generated by Django 4.1.9 on 2023-06-07 22:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
